spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  database:
    driverClassName: "com.mysql.jdbc.Driver"
  datasource:
    url: "jdbc:mysql://localhost:3306/itemsharingdatabase"
    username: "root"
    password: "{cipher} c19b574fc36b16be2f2e03378dc310f99d79396e6a83ba03e6d3128180cd2196"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"

server:
  port: 8082

